### ISSUE TITLE
Add postgres user

### ISSUE THREAD

**Issue by dragon-dxw** [dxw/local-env#18]
Brew doesn't set up a postgres user.

Add `/usr/local/opt/postgres/bin/createuser -s postgres || true` to the setup script (it will fail if the user already exists)

Via: https://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist#comment91332745_15309551

**Comment by erbridge** [comment]
So after doing a fresh Postgres reinstall, I needed to create a DB for my user (not `postgres`). I did that via `createdb`  (no arguments).

**Comment by yndajas** [comment]
`/usr/local/opt/` is the Intel/x86 path, but I ended up doing this instead:

- `psql postgres`
- `create user postgres with encrypted password 'WHATEVER_PASSWORD';
- `alter user postgres with superuser;` (and a few other alterations, but I think superuser supercedes them all)

**Comment by erbridge** [comment]
https://github.com/dxw/local-env/pull/19#issuecomment-964125616
