### ISSUE TITLE
Brew issues

### ISSUE THREAD

**Issue by dragon-dxw** [dxw/local-env#23]
Brew reported three unsuccessful installations (Slack and Onepassword were I think seen) and the installation script stopped at the end of that command.

Additionally, when running `brew install nodenv`:

```
Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
Please create a new installation in /opt/homebrew using one of the
“Alternative Installs” from:
 https://docs.brew.sh/Installation
You can migrate your previously installed formula list with:
 brew bundle dump
 ```

**Comment by snim2** [comment]
> I think I had a similar issue with the script exiting early if any installations fail, in my case also because I already had a couple things already installed (Slack and Chrome). At the end of the [Homebrew dependencies section](https://github.com/dxw/local-env/blob/main/install#L78-L86) I got the following and the script exited without getting onto the ZSH or choices sections
> 
> ```shell
> Homebrew Bundle failed! 2 Brewfile dependencies failed to install.
> ```

Likewise, I already had Slack, Zoom and Chrome installed and the script ended here:

```sh
==> Installing Cask visual-studio-code
==> Moving App 'Visual Studio Code.app' to '/Applications/Visual Studio Code.app'
==> Linking Binary 'code' to '/opt/homebrew/bin/code'
🍺  visual-studio-code was successfully installed!
Homebrew Bundle failed! 3 Brewfile dependencies failed to install.
```
> 
> I think #24 addresses the second (sub)issue @dragon-dxw raised but not the first (since it's just a documentation PR)?

Yes, I'll remove the `Closes...`
