### ISSUE TITLE
Starship font support

### ISSUE THREAD

**Issue by yndajas** [dxw/local-env#25]
## Issue

The script installs Starship (via the Brewfile), which by default has a Nerd Font prerequisite, but the script doesn't cover this. Without it, various icons that Starship uses to represent technologies like Git will appear as question mark boxes

### Option 1: mostly automatic

- Extend the Brewfile to include [font installation via Homebrew](https://github.com/ryanoasis/nerd-fonts#option-4-homebrew-fonts) (installing the Nerd Font version of something like Fira Code, Hack, Meslo or Source Code Pro)
- Update the guide to instruct people to update their terminal emulator to use the installed font

### Option 2: manual

Update the guide to instruct people to:
- [install a Nerd Font by their chosen means](https://github.com/ryanoasis/nerd-fonts#font-installation)
- update their terminal emulator to use the installed font

**Comment by erbridge** [comment]
I like either option 1 but automating the font settings or dropping Starship in favour of something else. The aim of this script is to be as low interaction as possible, and for something like a prompt, I don't think it's worth leaving people with required follow up actions they need to take.
