### ISSUE TITLE
Advice for devs using 1Password as an SSH agent

### ISSUE THREAD

**Issue by snim2** [dxw/local-env#28]
[It is now possible to use 1Password as an SSH agent](https://developer.1password.com/docs/ssh/), and to add keys for authentication and for [Git commit signing](https://blog.1password.com/git-commit-signing/) (although signing is currently [only available in GitHub](https://gitlab.com/gitlab-org/gitlab/-/issues/343879)).

Since the `local-env` script installs a `.zshrc` config which starts `ssh-agent`, any dev using 1Password like this will need to replace:

```shell
if command -v ssh-agent >/dev/null 2>&1; then
  eval "$(ssh-agent)"
  ssh-add --apple-load-keychain
fi
```

with this config, which is [documented here](https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client):

```shell
# Use 1Password as an ssh-agent.
export SSH_AUTH_SOCK=$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
```

because [1Password is not compatible](https://developer.1password.com/docs/ssh/agent/compatibility/) with the OpenSSH version of `ssh-add`.

It would be useful (I think) to have some documentation that explains this somewhere, but I'd imagine that different devs use different SSH agents, so maybe we don't want to make it default?

I'd be happy to raise a PR for this, but it's not clear to me whether it's better to put some notes in `README.md` or somewhere else...

**Comment by erbridge** [comment]
I think a comment adjacent to the code block you referenced might be the thing to do here. I'm not sure _why_ I'd use 1Password over OpenSSH, personally, so if we're going to default to something, by strong vote would be to use the industry standard and not the proprietary thing.
